# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: info@trap9.io
  facebook:
  flickr:
  github: trap9/trap9.github.io/
  instagram:
  linkedin:
  pinterest:
  rss: yes # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: trap9io
  stackoverflow: # your stackoverflow profile, e.g. "users/12345/usernick"


# Dependencies
markdown:         kramdown

kramdown:
 input: GFM

highlighter:      pygments

excerpt_separator: "\n\n"

# Permalinks
permalink:        pretty

# Setup
title:            trap9.io
tagline:          'signals uninterrupted'
description:      "A diary of one man\'s journey into signal perception and interpretation."
url:              http://trap9.io
baseurl:          '/'
paginate:         5


# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/trap9/trap9.github.io

  # Set the Sass partials directory, as we're using @imports
#sass:
 # sass_dir: _scss
 # style: :expanded # You might prefer to minify using :compressed
