# Dependencies
markdown:         kramdown

kramdown:
 input: GFM

highlighter:      pygments

excerpt_separator: "\n\n"

# Permalinks
permalink:        pretty

# Setup
title:            trap9.io
tagline:          'signals uninterrupted'
description:      "A diary of one man\'s journey into signal perception and interpretation."
url:              http://trap9.io
baseurl:          '/'
paginate:         5

author:
  name:           'Jiri Zoth'
  url:            https://twitter.com/jzoaka

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/trap9/trap9.github.io
